package edu.ou.herbarium.main;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * DataUtilsService service = new DataUtilsService();
 * DataUtilsDelegate portType = service.getDataUtilsPort();
 * portType.getParent(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "DataUtilsService", targetNamespace = "http://main.herbarium.ou.edu/", wsdlLocation = "http://localhost:8081/HerbService/DataUtilsPort?wsdl")
public class DataUtilsService extends Service {

	private final static URL DATAUTILSSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(edu.ou.herbarium.main.DataUtilsService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = edu.ou.herbarium.main.DataUtilsService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://localhost:8081/HerbService/DataUtilsPort?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8081/HerbService/DataUtilsPort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		DATAUTILSSERVICE_WSDL_LOCATION = url;
	}

	public DataUtilsService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public DataUtilsService() {
		super(DATAUTILSSERVICE_WSDL_LOCATION, new QName(
				"http://main.herbarium.ou.edu/", "DataUtilsService"));
	}

	/**
	 * 
	 * @return returns DataUtilsDelegate
	 */
	@WebEndpoint(name = "DataUtilsPort")
	public DataUtilsDelegate getDataUtilsPort() {
		return super.getPort(new QName("http://main.herbarium.ou.edu/",
				"DataUtilsPort"), DataUtilsDelegate.class);
	}

}
