package edu.ou.herbarium.main;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "DataUtilsDelegate", targetNamespace = "http://main.herbarium.ou.edu/")
public interface DataUtilsDelegate {

	/**
	 * 
	 * @param arg0
	 * @return returns edu.ou.herbarium.main.Folder
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getParent", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.GetParent")
	@ResponseWrapper(localName = "getParentResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.GetParentResponse")
	public Folder getParent(
			@WebParam(name = "arg0", targetNamespace = "") Integer arg0);

	/**
	 * 
	 * @return returns java.util.List<edu.ou.herbarium.main.Collection>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getCollections", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.GetCollections")
	@ResponseWrapper(localName = "getCollectionsResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.GetCollectionsResponse")
	public List<Collection> getCollections();

	/**
	 * 
	 * @return returns java.util.List<edu.ou.herbarium.main.User>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getUsers", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.GetUsers")
	@ResponseWrapper(localName = "getUsersResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.GetUsersResponse")
	public List<User> getUsers();

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "setPort", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.SetPort")
	@ResponseWrapper(localName = "setPortResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.SetPortResponse")
	public void setPort(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<edu.ou.herbarium.main.SystemSetting>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getSettings", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.GetSettings")
	@ResponseWrapper(localName = "getSettingsResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.GetSettingsResponse")
	public List<SystemSetting> getSettings(
			@WebParam(name = "arg0", targetNamespace = "") Integer arg0);

	/**
	 * 
	 * @return returns java.util.List<edu.ou.herbarium.main.Folder>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getFolders", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.GetFolders")
	@ResponseWrapper(localName = "getFoldersResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.GetFoldersResponse")
	public List<Folder> getFolders();

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<edu.ou.herbarium.main.Authority>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getAuthorities", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.GetAuthorities")
	@ResponseWrapper(localName = "getAuthoritiesResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.GetAuthoritiesResponse")
	public List<Authority> getAuthorities(
			@WebParam(name = "arg0", targetNamespace = "") int arg0);

	/**
	 * 
	 * @return returns edu.ou.herbarium.main.Folder
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getTopFolders", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.GetTopFolders")
	@ResponseWrapper(localName = "getTopFoldersResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.GetTopFoldersResponse")
	public Folder getTopFolders();

	/**
	 * 
	 * @return returns java.util.List<edu.ou.herbarium.main.Specimen>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getSpecimens", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.GetSpecimens")
	@ResponseWrapper(localName = "getSpecimensResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.GetSpecimensResponse")
	public List<Specimen> getSpecimens();

	/**
	 * 
	 * @param arg0
	 * @return returns edu.ou.herbarium.main.ImageRaw
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getImageRaw", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.GetImageRaw")
	@ResponseWrapper(localName = "getImageRawResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.GetImageRawResponse")
	public ImageRaw getImageRaw(
			@WebParam(name = "arg0", targetNamespace = "") int arg0);

	/**
	 * 
	 * @return returns java.util.List<edu.ou.herbarium.main.Institute>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getInstitutes", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.GetInstitutes")
	@ResponseWrapper(localName = "getInstitutesResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.GetInstitutesResponse")
	public List<Institute> getInstitutes();

	/**
	 * 
	 * @param arg0
	 * @return returns edu.ou.herbarium.main.Institute
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "updateInstitute", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.UpdateInstitute")
	@ResponseWrapper(localName = "updateInstituteResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.UpdateInstituteResponse")
	public Institute updateInstitute(
			@WebParam(name = "arg0", targetNamespace = "") Institute arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "deleteInstitute", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.DeleteInstitute")
	@ResponseWrapper(localName = "deleteInstituteResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.DeleteInstituteResponse")
	public void deleteInstitute(
			@WebParam(name = "arg0", targetNamespace = "") Institute arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns edu.ou.herbarium.main.Institute
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "insertInstitute", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.InsertInstitute")
	@ResponseWrapper(localName = "insertInstituteResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.InsertInstituteResponse")
	public Institute insertInstitute(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<edu.ou.herbarium.main.Specimen>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getSpecimensByFolder", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.GetSpecimensByFolder")
	@ResponseWrapper(localName = "getSpecimensByFolderResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.GetSpecimensByFolderResponse")
	public List<Specimen> getSpecimensByFolder(
			@WebParam(name = "arg0", targetNamespace = "") int arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns int
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getSpecimenNumberByFolder", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.GetSpecimenNumberByFolder")
	@ResponseWrapper(localName = "getSpecimenNumberByFolderResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.GetSpecimenNumberByFolderResponse")
	public int getSpecimenNumberByFolder(
			@WebParam(name = "arg0", targetNamespace = "") int arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.util.List<edu.ou.herbarium.main.Specimen>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getSpecimensByWeek", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.GetSpecimensByWeek")
	@ResponseWrapper(localName = "getSpecimensByWeekResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.GetSpecimensByWeekResponse")
	public List<Specimen> getSpecimensByWeek(
			@WebParam(name = "arg0", targetNamespace = "") int arg0,
			@WebParam(name = "arg1", targetNamespace = "") int arg1);

	/**
	 * 
	 * @param arg0
	 * @return returns edu.ou.herbarium.main.Specimen
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getSpecimenById", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.GetSpecimenById")
	@ResponseWrapper(localName = "getSpecimenByIdResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.GetSpecimenByIdResponse")
	public Specimen getSpecimenById(
			@WebParam(name = "arg0", targetNamespace = "") int arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.util.List<edu.ou.herbarium.main.Specimen>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getSpecimens2", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.GetSpecimens2")
	@ResponseWrapper(localName = "getSpecimens2Response", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.GetSpecimens2Response")
	public List<Specimen> getSpecimens2(
			@WebParam(name = "arg0", targetNamespace = "") int arg0,
			@WebParam(name = "arg1", targetNamespace = "") int arg1);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns edu.ou.herbarium.main.User
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "validateLogin", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.ValidateLogin")
	@ResponseWrapper(localName = "validateLoginResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.ValidateLoginResponse")
	public User validateLogin(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "updateUser", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.UpdateUser")
	@ResponseWrapper(localName = "updateUserResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.UpdateUserResponse")
	public void updateUser(
			@WebParam(name = "arg0", targetNamespace = "") User arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns edu.ou.herbarium.main.Collector
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "insertCollector", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.InsertCollector")
	@ResponseWrapper(localName = "insertCollectorResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.InsertCollectorResponse")
	public Collector insertCollector(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg5
	 * @param arg4
	 * @param arg3
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @param arg6
	 * @return returns edu.ou.herbarium.main.Specimen
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "insertSpecimen", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.InsertSpecimen")
	@ResponseWrapper(localName = "insertSpecimenResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.InsertSpecimenResponse")
	public Specimen insertSpecimen(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") Specimen arg2,
			@WebParam(name = "arg3", targetNamespace = "") byte[] arg3,
			@WebParam(name = "arg4", targetNamespace = "") byte[] arg4,
			@WebParam(name = "arg5", targetNamespace = "") byte[] arg5,
			@WebParam(name = "arg6", targetNamespace = "") byte[] arg6);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "updateSpecimen", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.UpdateSpecimen")
	@ResponseWrapper(localName = "updateSpecimenResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.UpdateSpecimenResponse")
	public void updateSpecimen(
			@WebParam(name = "arg0", targetNamespace = "") Specimen arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<edu.ou.herbarium.main.Collector>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getCollectorsBySpecimen", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.GetCollectorsBySpecimen")
	@ResponseWrapper(localName = "getCollectorsBySpecimenResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.GetCollectorsBySpecimenResponse")
	public List<Collector> getCollectorsBySpecimen(
			@WebParam(name = "arg0", targetNamespace = "") Specimen arg0);

	/**
	 * 
	 * @return returns java.util.List<edu.ou.herbarium.main.Collector>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getCollectors", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.GetCollectors")
	@ResponseWrapper(localName = "getCollectorsResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.GetCollectorsResponse")
	public List<Collector> getCollectors();

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.util.List<edu.ou.herbarium.main.Collector>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getCollectorsByPage", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.GetCollectorsByPage")
	@ResponseWrapper(localName = "getCollectorsByPageResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.GetCollectorsByPageResponse")
	public List<Collector> getCollectorsByPage(
			@WebParam(name = "arg0", targetNamespace = "") int arg0,
			@WebParam(name = "arg1", targetNamespace = "") int arg1);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<edu.ou.herbarium.main.Collector>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getCollectorsByName", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.GetCollectorsByName")
	@ResponseWrapper(localName = "getCollectorsByNameResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.GetCollectorsByNameResponse")
	public List<Collector> getCollectorsByName(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "updateCollector", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.UpdateCollector")
	@ResponseWrapper(localName = "updateCollectorResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.UpdateCollectorResponse")
	public void updateCollector(
			@WebParam(name = "arg0", targetNamespace = "") Collector arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns edu.ou.herbarium.main.User
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getUserByName", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.GetUserByName")
	@ResponseWrapper(localName = "getUserByNameResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.GetUserByNameResponse")
	public User getUserByName(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg5
	 * @param arg4
	 * @param arg3
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @param arg6
	 * @return returns edu.ou.herbarium.main.User
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "insertUser", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.InsertUser")
	@ResponseWrapper(localName = "insertUserResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.InsertUserResponse")
	public User insertUser(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2,
			@WebParam(name = "arg3", targetNamespace = "") String arg3,
			@WebParam(name = "arg4", targetNamespace = "") String arg4,
			@WebParam(name = "arg5", targetNamespace = "") String arg5,
			@WebParam(name = "arg6", targetNamespace = "") String arg6);

	/**
	 * 
	 * @param arg0
	 * @return returns edu.ou.herbarium.main.Collector
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "insertCollector2", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.InsertCollector2")
	@ResponseWrapper(localName = "insertCollector2Response", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.InsertCollector2Response")
	public Collector insertCollector2(
			@WebParam(name = "arg0", targetNamespace = "") Collector arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns edu.ou.herbarium.main.System
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "insertSystem", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.InsertSystem")
	@ResponseWrapper(localName = "insertSystemResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.InsertSystemResponse")
	public System insertSystem(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") int arg1);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns edu.ou.herbarium.main.System
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "updateSystem", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.UpdateSystem")
	@ResponseWrapper(localName = "updateSystemResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.UpdateSystemResponse")
	public System updateSystem(
			@WebParam(name = "arg0", targetNamespace = "") System arg0,
			@WebParam(name = "arg1", targetNamespace = "") int arg1);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns edu.ou.herbarium.main.System
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "deleteSystem", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.DeleteSystem")
	@ResponseWrapper(localName = "deleteSystemResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.DeleteSystemResponse")
	public System deleteSystem(
			@WebParam(name = "arg0", targetNamespace = "") System arg0,
			@WebParam(name = "arg1", targetNamespace = "") Integer arg1);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<edu.ou.herbarium.main.System>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getSystems", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.GetSystems")
	@ResponseWrapper(localName = "getSystemsResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.GetSystemsResponse")
	public List<System> getSystems(
			@WebParam(name = "arg0", targetNamespace = "") Integer arg0);

	/**
	 * 
	 * @param arg5
	 * @param arg4
	 * @param arg3
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @param arg6
	 * @param arg7
	 * @param arg8
	 * @param arg9
	 * @return returns edu.ou.herbarium.main.SystemSetting
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "insertSystemSetting", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.InsertSystemSetting")
	@ResponseWrapper(localName = "insertSystemSettingResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.InsertSystemSettingResponse")
	public SystemSetting insertSystemSetting(
			@WebParam(name = "arg0", targetNamespace = "") Integer arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2,
			@WebParam(name = "arg3", targetNamespace = "") Integer arg3,
			@WebParam(name = "arg4", targetNamespace = "") Integer arg4,
			@WebParam(name = "arg5", targetNamespace = "") Integer arg5,
			@WebParam(name = "arg6", targetNamespace = "") Integer arg6,
			@WebParam(name = "arg7", targetNamespace = "") Integer arg7,
			@WebParam(name = "arg8", targetNamespace = "") Integer arg8,
			@WebParam(name = "arg9", targetNamespace = "") String arg9);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns edu.ou.herbarium.main.SystemSetting
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "updateSystemSetting", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.UpdateSystemSetting")
	@ResponseWrapper(localName = "updateSystemSettingResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.UpdateSystemSettingResponse")
	public SystemSetting updateSystemSetting(
			@WebParam(name = "arg0", targetNamespace = "") SystemSetting arg0,
			@WebParam(name = "arg1", targetNamespace = "") System arg1);

	/**
	 * 
	 * @param arg0
	 * @return returns edu.ou.herbarium.main.SystemSetting
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "deleteSystemSetting", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.DeleteSystemSetting")
	@ResponseWrapper(localName = "deleteSystemSettingResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.DeleteSystemSettingResponse")
	public SystemSetting deleteSystemSetting(
			@WebParam(name = "arg0", targetNamespace = "") SystemSetting arg0);

	/**
	 * 
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns edu.ou.herbarium.main.Folder
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "insertFolder", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.InsertFolder")
	@ResponseWrapper(localName = "insertFolderResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "edu.ou.herbarium.main.InsertFolderResponse")
	public Folder insertFolder(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2);

}
