package org.nevp.herbarium.wsclient;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "DataUtilsDelegate", targetNamespace = "http://main.herbarium.ou.edu/")
public interface DataUtilsDelegate {

	/**
	 * 
	 * @param arg0
	 * @return returns org.nevp.herbarium.wsclient.Folder
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getParent", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.GetParent")
	@ResponseWrapper(localName = "getParentResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.GetParentResponse")
	public Folder getParent(
			@WebParam(name = "arg0", targetNamespace = "") Integer arg0);

	/**
	 * 
	 * @return returns java.util.List<org.nevp.herbarium.wsclient.Collection>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getCollections", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.GetCollections")
	@ResponseWrapper(localName = "getCollectionsResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.GetCollectionsResponse")
	public List<Collection> getCollections();

	/**
	 * 
	 * @return returns java.util.List<org.nevp.herbarium.wsclient.User>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getUsers", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.GetUsers")
	@ResponseWrapper(localName = "getUsersResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.GetUsersResponse")
	public List<User> getUsers();

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "setPort", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.SetPort")
	@ResponseWrapper(localName = "setPortResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.SetPortResponse")
	public void setPort(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<org.nevp.herbarium.wsclient.SystemSetting>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getSettings", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.GetSettings")
	@ResponseWrapper(localName = "getSettingsResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.GetSettingsResponse")
	public List<SystemSetting> getSettings(
			@WebParam(name = "arg0", targetNamespace = "") Integer arg0);

	/**
	 * 
	 * @return returns java.util.List<org.nevp.herbarium.wsclient.Folder>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getFolders", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.GetFolders")
	@ResponseWrapper(localName = "getFoldersResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.GetFoldersResponse")
	public List<Folder> getFolders();

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<org.nevp.herbarium.wsclient.Authority>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getAuthorities", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.GetAuthorities")
	@ResponseWrapper(localName = "getAuthoritiesResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.GetAuthoritiesResponse")
	public List<Authority> getAuthorities(
			@WebParam(name = "arg0", targetNamespace = "") int arg0);

	/**
	 * 
	 * @return returns org.nevp.herbarium.wsclient.Folder
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getTopFolders", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.GetTopFolders")
	@ResponseWrapper(localName = "getTopFoldersResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.GetTopFoldersResponse")
	public Folder getTopFolders();

	/**
	 * 
	 * @return returns java.util.List<org.nevp.herbarium.wsclient.Specimen>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getSpecimens", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.GetSpecimens")
	@ResponseWrapper(localName = "getSpecimensResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.GetSpecimensResponse")
	public List<Specimen> getSpecimens();

	/**
	 * 
	 * @param arg0
	 * @return returns org.nevp.herbarium.wsclient.ImageRaw
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getImageRaw", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.GetImageRaw")
	@ResponseWrapper(localName = "getImageRawResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.GetImageRawResponse")
	public ImageRaw getImageRaw(
			@WebParam(name = "arg0", targetNamespace = "") int arg0);

	/**
	 * 
	 * @return returns java.util.List<org.nevp.herbarium.wsclient.Institute>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getInstitutes", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.GetInstitutes")
	@ResponseWrapper(localName = "getInstitutesResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.GetInstitutesResponse")
	public List<Institute> getInstitutes();

	/**
	 * 
	 * @param arg0
	 * @return returns org.nevp.herbarium.wsclient.Institute
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "updateInstitute", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.UpdateInstitute")
	@ResponseWrapper(localName = "updateInstituteResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.UpdateInstituteResponse")
	public Institute updateInstitute(
			@WebParam(name = "arg0", targetNamespace = "") Institute arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "deleteInstitute", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.DeleteInstitute")
	@ResponseWrapper(localName = "deleteInstituteResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.DeleteInstituteResponse")
	public void deleteInstitute(
			@WebParam(name = "arg0", targetNamespace = "") Institute arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns org.nevp.herbarium.wsclient.Institute
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "insertInstitute", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.InsertInstitute")
	@ResponseWrapper(localName = "insertInstituteResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.InsertInstituteResponse")
	public Institute insertInstitute(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<org.nevp.herbarium.wsclient.Specimen>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getSpecimensByFolder", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.GetSpecimensByFolder")
	@ResponseWrapper(localName = "getSpecimensByFolderResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.GetSpecimensByFolderResponse")
	public List<Specimen> getSpecimensByFolder(
			@WebParam(name = "arg0", targetNamespace = "") int arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns int
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getSpecimenNumberByFolder", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.GetSpecimenNumberByFolder")
	@ResponseWrapper(localName = "getSpecimenNumberByFolderResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.GetSpecimenNumberByFolderResponse")
	public int getSpecimenNumberByFolder(
			@WebParam(name = "arg0", targetNamespace = "") int arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.util.List<org.nevp.herbarium.wsclient.Specimen>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getSpecimensByWeek", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.GetSpecimensByWeek")
	@ResponseWrapper(localName = "getSpecimensByWeekResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.GetSpecimensByWeekResponse")
	public List<Specimen> getSpecimensByWeek(
			@WebParam(name = "arg0", targetNamespace = "") int arg0,
			@WebParam(name = "arg1", targetNamespace = "") int arg1);

	/**
	 * 
	 * @param arg0
	 * @return returns org.nevp.herbarium.wsclient.Specimen
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getSpecimenById", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.GetSpecimenById")
	@ResponseWrapper(localName = "getSpecimenByIdResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.GetSpecimenByIdResponse")
	public Specimen getSpecimenById(
			@WebParam(name = "arg0", targetNamespace = "") int arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.util.List<org.nevp.herbarium.wsclient.Specimen>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getSpecimens2", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.GetSpecimens2")
	@ResponseWrapper(localName = "getSpecimens2Response", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.GetSpecimens2Response")
	public List<Specimen> getSpecimens2(
			@WebParam(name = "arg0", targetNamespace = "") int arg0,
			@WebParam(name = "arg1", targetNamespace = "") int arg1);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns org.nevp.herbarium.wsclient.User
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "validateLogin", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.ValidateLogin")
	@ResponseWrapper(localName = "validateLoginResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.ValidateLoginResponse")
	public User validateLogin(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "updateUser", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.UpdateUser")
	@ResponseWrapper(localName = "updateUserResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.UpdateUserResponse")
	public void updateUser(
			@WebParam(name = "arg0", targetNamespace = "") User arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns org.nevp.herbarium.wsclient.Collector
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "insertCollector", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.InsertCollector")
	@ResponseWrapper(localName = "insertCollectorResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.InsertCollectorResponse")
	public Collector insertCollector(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg5
	 * @param arg4
	 * @param arg3
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @param arg6
	 * @return returns org.nevp.herbarium.wsclient.Specimen
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "insertSpecimen", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.InsertSpecimen")
	@ResponseWrapper(localName = "insertSpecimenResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.InsertSpecimenResponse")
	public Specimen insertSpecimen(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") Specimen arg2,
			@WebParam(name = "arg3", targetNamespace = "") byte[] arg3,
			@WebParam(name = "arg4", targetNamespace = "") byte[] arg4,
			@WebParam(name = "arg5", targetNamespace = "") byte[] arg5,
			@WebParam(name = "arg6", targetNamespace = "") byte[] arg6);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "updateSpecimen", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.UpdateSpecimen")
	@ResponseWrapper(localName = "updateSpecimenResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.UpdateSpecimenResponse")
	public void updateSpecimen(
			@WebParam(name = "arg0", targetNamespace = "") Specimen arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<org.nevp.herbarium.wsclient.Collector>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getCollectorsBySpecimen", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.GetCollectorsBySpecimen")
	@ResponseWrapper(localName = "getCollectorsBySpecimenResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.GetCollectorsBySpecimenResponse")
	public List<Collector> getCollectorsBySpecimen(
			@WebParam(name = "arg0", targetNamespace = "") Specimen arg0);

	/**
	 * 
	 * @return returns java.util.List<org.nevp.herbarium.wsclient.Collector>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getCollectors", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.GetCollectors")
	@ResponseWrapper(localName = "getCollectorsResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.GetCollectorsResponse")
	public List<Collector> getCollectors();

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.util.List<org.nevp.herbarium.wsclient.Collector>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getCollectorsByPage", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.GetCollectorsByPage")
	@ResponseWrapper(localName = "getCollectorsByPageResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.GetCollectorsByPageResponse")
	public List<Collector> getCollectorsByPage(
			@WebParam(name = "arg0", targetNamespace = "") int arg0,
			@WebParam(name = "arg1", targetNamespace = "") int arg1);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<org.nevp.herbarium.wsclient.Collector>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getCollectorsByName", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.GetCollectorsByName")
	@ResponseWrapper(localName = "getCollectorsByNameResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.GetCollectorsByNameResponse")
	public List<Collector> getCollectorsByName(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "updateCollector", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.UpdateCollector")
	@ResponseWrapper(localName = "updateCollectorResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.UpdateCollectorResponse")
	public void updateCollector(
			@WebParam(name = "arg0", targetNamespace = "") Collector arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns org.nevp.herbarium.wsclient.User
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getUserByName", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.GetUserByName")
	@ResponseWrapper(localName = "getUserByNameResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.GetUserByNameResponse")
	public User getUserByName(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg5
	 * @param arg4
	 * @param arg3
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @param arg6
	 * @return returns org.nevp.herbarium.wsclient.User
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "insertUser", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.InsertUser")
	@ResponseWrapper(localName = "insertUserResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.InsertUserResponse")
	public User insertUser(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2,
			@WebParam(name = "arg3", targetNamespace = "") String arg3,
			@WebParam(name = "arg4", targetNamespace = "") String arg4,
			@WebParam(name = "arg5", targetNamespace = "") String arg5,
			@WebParam(name = "arg6", targetNamespace = "") String arg6);

	/**
	 * 
	 * @param arg0
	 * @return returns org.nevp.herbarium.wsclient.Collector
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "insertCollector2", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.InsertCollector2")
	@ResponseWrapper(localName = "insertCollector2Response", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.InsertCollector2Response")
	public Collector insertCollector2(
			@WebParam(name = "arg0", targetNamespace = "") Collector arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns org.nevp.herbarium.wsclient.System
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "insertSystem", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.InsertSystem")
	@ResponseWrapper(localName = "insertSystemResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.InsertSystemResponse")
	public System insertSystem(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") int arg1);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns org.nevp.herbarium.wsclient.System
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "updateSystem", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.UpdateSystem")
	@ResponseWrapper(localName = "updateSystemResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.UpdateSystemResponse")
	public System updateSystem(
			@WebParam(name = "arg0", targetNamespace = "") System arg0,
			@WebParam(name = "arg1", targetNamespace = "") int arg1);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns org.nevp.herbarium.wsclient.System
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "deleteSystem", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.DeleteSystem")
	@ResponseWrapper(localName = "deleteSystemResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.DeleteSystemResponse")
	public System deleteSystem(
			@WebParam(name = "arg0", targetNamespace = "") System arg0,
			@WebParam(name = "arg1", targetNamespace = "") Integer arg1);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<org.nevp.herbarium.wsclient.System>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getSystems", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.GetSystems")
	@ResponseWrapper(localName = "getSystemsResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.GetSystemsResponse")
	public List<System> getSystems(
			@WebParam(name = "arg0", targetNamespace = "") Integer arg0);

	/**
	 * 
	 * @param arg5
	 * @param arg4
	 * @param arg3
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @param arg6
	 * @param arg7
	 * @param arg8
	 * @param arg9
	 * @return returns org.nevp.herbarium.wsclient.SystemSetting
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "insertSystemSetting", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.InsertSystemSetting")
	@ResponseWrapper(localName = "insertSystemSettingResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.InsertSystemSettingResponse")
	public SystemSetting insertSystemSetting(
			@WebParam(name = "arg0", targetNamespace = "") Integer arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2,
			@WebParam(name = "arg3", targetNamespace = "") Integer arg3,
			@WebParam(name = "arg4", targetNamespace = "") Integer arg4,
			@WebParam(name = "arg5", targetNamespace = "") Integer arg5,
			@WebParam(name = "arg6", targetNamespace = "") Integer arg6,
			@WebParam(name = "arg7", targetNamespace = "") Integer arg7,
			@WebParam(name = "arg8", targetNamespace = "") Integer arg8,
			@WebParam(name = "arg9", targetNamespace = "") String arg9);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns org.nevp.herbarium.wsclient.SystemSetting
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "updateSystemSetting", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.UpdateSystemSetting")
	@ResponseWrapper(localName = "updateSystemSettingResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.UpdateSystemSettingResponse")
	public SystemSetting updateSystemSetting(
			@WebParam(name = "arg0", targetNamespace = "") SystemSetting arg0,
			@WebParam(name = "arg1", targetNamespace = "") System arg1);

	/**
	 * 
	 * @param arg0
	 * @return returns org.nevp.herbarium.wsclient.SystemSetting
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "deleteSystemSetting", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.DeleteSystemSetting")
	@ResponseWrapper(localName = "deleteSystemSettingResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.DeleteSystemSettingResponse")
	public SystemSetting deleteSystemSetting(
			@WebParam(name = "arg0", targetNamespace = "") SystemSetting arg0);

	/**
	 * 
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns org.nevp.herbarium.wsclient.Folder
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "insertFolder", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.InsertFolder")
	@ResponseWrapper(localName = "insertFolderResponse", targetNamespace = "http://main.herbarium.ou.edu/", className = "org.nevp.herbarium.wsclient.InsertFolderResponse")
	public Folder insertFolder(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2);

}
